window.OLTRE_INITIAL_PRODUCTS = [
    {
        "id":  140,
        "name":  "Trocar Batatas por Batatas com Queijo e Bacon",
        "category":  "adicionar-extras",
        "categoryName":  "ADICIONAR EXTRAS",
        "description":  "",
        "price":  4,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  139,
        "name":  "Oltre Chimichurri",
        "category":  "burgers",
        "categoryName":  "Burgers",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1304/conversions/WhatsApp-Image-2024-06-03-at-14.25.43-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  138,
        "name":  "Oltre Chimichurri",
        "category":  "escolha-a-bebida-gratis",
        "categoryName":  "ESCOLHA A BEBIDA GRÁTIS",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1302/conversions/WhatsApp-Image-2024-06-03-at-14.25.43-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  137,
        "name":  "Banoffee",
        "category":  "sobremesas",
        "categoryName":  "SOBREMESAS",
        "description":  "",
        "price":  5,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1301/conversions/BANOFFEE-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  136,
        "name":  "EMBALAGEM ENTRADAS",
        "category":  "embalagem-obrigatorio",
        "categoryName":  "EMBALAGEM OBRIGATORIO - Decreto-Lei n.º 102-D/2020",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  135,
        "name":  "EMBALAGEM HAMBURGUER - Decreto-Lei n.º 102-D/2020",
        "category":  "embalagem-obrigatorio",
        "categoryName":  "EMBALAGEM OBRIGATORIO - Decreto-Lei n.º 102-D/2020",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  134,
        "name":  "MOLHO DE QUEIJO",
        "category":  "adicionar-extras",
        "categoryName":  "ADICIONAR EXTRAS",
        "description":  "",
        "price":  3,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  133,
        "name":  "OLTRE SPECIAL 20% DESCONTO",
        "category":  "promocoes",
        "categoryName":  "PROMOÇÕES",
        "description":  "Oltre Special com 20% de desconto!!\nAproveite agora nossa promoção!\nPeça já o seu!",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1290/conversions/Texto-do-seu-par%C3%A1grafo-%286%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  132,
        "name":  "OLTRE CHICKEN BACON 20% DESCONTO",
        "category":  "promocoes",
        "categoryName":  "PROMOÇÕES",
        "description":  "Oltre Chicken Bacon com 20% de desconto!!\nAproveite agora nossa promoção!\nPeça já o seu!",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1289/conversions/Texto-do-seu-par%C3%A1grafo-%285%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  131,
        "name":  "OLTRE BACON 20% DESCONTO",
        "category":  "promocoes",
        "categoryName":  "PROMOÇÕES",
        "description":  "Oltre Bacon com 20% de desconto!!\nAproveite agora nossa promoção!\nPeça já o seu!",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1288/conversions/Texto-do-seu-par%C3%A1grafo-%284%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  128,
        "name":  "CHICKEN WINGS 20% DESCONTO",
        "category":  "promocoes",
        "categoryName":  "PROMOÇÕES",
        "description":  "Chicken Wings com 20% de desconto!!\nAproveite agora nossa promoção!\nPeça já o seu!",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1285/conversions/Texto-do-seu-par%C3%A1grafo-%283%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  126,
        "name":  "COMPRE 2 GANHE 1 TIRAMISÙ",
        "category":  "promocoes",
        "categoryName":  "PROMOÇÕES",
        "description":  "Ganhe 1 TIRAMISÙ!!\nPromoção imperdível!\nCompre dois deliciosos hambúrgueres e ganhe um tiramisù gráis. Aproveite esse combo irresistível e saboreie uma refeição completa com uma sobremesa deliciosa. Não deixe essa oportunidade escapar venha aproveitar essa promoção agora mesmo!",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1282/conversions/Texto-do-seu-par%C3%A1grafo-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  125,
        "name":  "Tiramisù",
        "category":  "sobremesas",
        "categoryName":  "SOBREMESAS",
        "description":  "Sobremesa de origem italiana confecionada artesanalmente, e este tiramisù especialmente faz sucesso na hamburgueria.",
        "price":  5,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1276/conversions/TIRAMISU-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  124,
        "name":  "COMPRE 2 (SOMENTE NO SITE) GANHE 1 BEBIDA",
        "category":  "promocoes",
        "categoryName":  "PROMOÇÕES",
        "description":  "Ganhe uma BEBIDA!!\nPromoção imperdível!\nCompre dois deliciosos hambúrgueres e ganhe uma bebida gráis. Aproveite esse combo irresistível e saboreie uma refeição completa com um refresco delicioso. Não deixe essa oportunidade escapar venha aproveitar essa promoção agora mesmo!",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1283/conversions/Texto-do-seu-par%C3%A1grafo-%281%29-thumbnail.jpg",
        "badge":  "Destaque"
    },
    {
        "id":  123,
        "name":  "Oltre Vegetarian",
        "category":  "escolha-o-hamburguer",
        "categoryName":  "Escolha o Hamburguer",
        "description":  "Pão artesanal, cogumelo portobello, courgette, beringela, tomate, anéis de cebola, rúcula, molho Oltre e batata rústica.",
        "price":  12,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1254/conversions/Design-sem-nome-%2885%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  122,
        "name":  "Oltre Pulled Beef",
        "category":  "escolha-o-hamburguer",
        "categoryName":  "Escolha o Hamburguer",
        "description":  "Pão artesanal, carne de vaca fumada e desfiada, salada coleslaw, molho barbecue artesanal e batata rústica.",
        "price":  11,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1253/conversions/Design-sem-nome-%2886%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  121,
        "name":  "Oltre Pulled Pork",
        "category":  "escolha-o-hamburguer",
        "categoryName":  "Escolha o Hamburguer",
        "description":  "Pão artesanal, carne de porco fumada e desfiada, salada coleslaw, molho barbecue artesanal e batata rústica.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1252/conversions/Design-sem-nome-%2887%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  120,
        "name":  "Oltre Smash",
        "category":  "escolha-o-hamburguer",
        "categoryName":  "Escolha o Hamburguer",
        "description":  "",
        "price":  8,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1251/conversions/Design-sem-nome-%2888%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  119,
        "name":  "Oltre Double Smash",
        "category":  "escolha-o-hamburguer",
        "categoryName":  "Escolha o Hamburguer",
        "description":  "Pão artesanal, 2x 80g de burger prensado, queijo cheddar, molho Oltre e batata rústica.",
        "price":  10,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1250/conversions/Design-sem-nome-%2889%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  118,
        "name":  "Oltre Triple Smash",
        "category":  "escolha-o-hamburguer",
        "categoryName":  "Escolha o Hamburguer",
        "description":  "Pão artesanal, 3x 80g de burger prensado, queijo cheddar, molho Oltre e batata rústica.",
        "price":  12,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1249/conversions/Design-sem-nome-%2890%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  117,
        "name":  "Oltre Chicken Burger",
        "category":  "escolha-o-hamburguer",
        "categoryName":  "Escolha o Hamburguer",
        "description":  "Pão artesanal, burger 100% peito de frango, queijo cheddar, molho Oltre e batata rústica.",
        "price":  9,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1248/conversions/Design-sem-nome-%2891%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  116,
        "name":  "Oltre Chicken Bacon",
        "category":  "escolha-o-hamburguer",
        "categoryName":  "Escolha o Hamburguer",
        "description":  "Pão artesanal, burger 100% peito de frango, queijo cheddar, bacon, cebola caramelizada, molho Oltre e batata rústica.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1247/conversions/Design-sem-nome-%2892%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  115,
        "name":  "Oltre Chicken Classic",
        "category":  "escolha-o-hamburguer",
        "categoryName":  "Escolha o Hamburguer",
        "description":  "Pão artesanal, burger 100% peito de frango, queijo cheddar, alface, tomate, picles de pepino, molho Oltre e batata rústica.",
        "price":  10,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1246/conversions/Design-sem-nome-%2893%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  114,
        "name":  "Oltre Chicken Egg",
        "category":  "escolha-o-hamburguer",
        "categoryName":  "Escolha o Hamburguer",
        "description":  "Pão artesanal, burger 100% peito de frango, queijo cheddar, bacon, cebola caramelizada, ovo frito, molho Oltre e batata rústica.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1245/conversions/Design-sem-nome-%2894%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  113,
        "name":  "Oltre Chicken Special",
        "category":  "escolha-o-hamburguer",
        "categoryName":  "Escolha o Hamburguer",
        "description":  "Pão artesanal, burger 100% peito de frango, queijo cheddar, bacon, cebola caramelizada, alface, tomate, picles de pepino, molho Oltre e batata rústica.",
        "price":  11,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1244/conversions/Design-sem-nome-%2895%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  112,
        "name":  "Oltre Burger",
        "category":  "escolha-o-hamburguer",
        "categoryName":  "Escolha o Hamburguer",
        "description":  "Pão artesanal, blend 100% vaca, queijo cheddar, molho Oltre e batata rústica.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1243/conversions/Design-sem-nome-%2896%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  111,
        "name":  "Oltre Bacon",
        "category":  "escolha-o-hamburguer",
        "categoryName":  "Escolha o Hamburguer",
        "description":  "Pão artesanal, blend 100% vaca, queijo cheddar, bacon defumado, cebola caramelizada, molho Oltre, e batata rústica.",
        "price":  11,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1242/conversions/Design-sem-nome-%2897%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  110,
        "name":  "Oltre Pepcream",
        "category":  "escolha-o-hamburguer",
        "categoryName":  "Escolha o Hamburguer",
        "description":  "Pão artesanal, blend 100% vaca, creme de queijo com pepperoni e batata rústica.",
        "price":  13,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1241/conversions/Design-sem-nome-%2899%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  109,
        "name":  "Oltre Old School",
        "category":  "escolha-o-hamburguer",
        "categoryName":  "Escolha o Hamburguer",
        "description":  "Pão artesanal, blend 100% vaca, queijo cheddar, cebola roxa, picles de pepino artesanal, ketchup, mostarda e batata rústica.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1240/conversions/Design-sem-nome-%28100%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  108,
        "name":  "Oltre Classic",
        "category":  "escolha-o-hamburguer",
        "categoryName":  "Escolha o Hamburguer",
        "description":  "Pão artesanal, blend 100% vaca, queijo cheddar, alface, tomate, picles de pepino, molho Oltre e batata rústica.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1239/conversions/Design-sem-nome---2023-06-01T144529.507-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  107,
        "name":  "Oltre Barbecue",
        "category":  "escolha-o-hamburguer",
        "categoryName":  "Escolha o Hamburguer",
        "description":  "Pão artesanal, blend 100% vaca, queijo cheddar, bacon fumado, onion rings , pickles artesanal de pepino e molho barbecue artesanal e batata rústica.",
        "price":  13,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1238/conversions/Design-sem-nome---2023-06-01T144616.217-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  106,
        "name":  "Cerveja Artesanal SAISON Garrafa 33cl. 6,2% Alc.",
        "category":  "cerveja",
        "categoryName":  "Cervejas",
        "description":  "Cerveja Aldeana.Loira, suave e delicada, a personificação perfeita da inspiração belga, de final seco e notas frutadas.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1205/conversions/Design-sem-nome-%2821%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  105,
        "name":  "Cerveja Artesanal STOUT Garrafa 33cl. 5,5% Alc.",
        "category":  "cerveja",
        "categoryName":  "Cervejas",
        "description":  "Cerveja Aldeana.Cerveja preta, de caráter intenso e cremoso onde sobressaem as notas torradas e de café.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1204/conversions/Design-sem-nome-%2820%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  104,
        "name":  "Cerveja Artesanal ORIGINAL Garrafa 33cl.  8,0% Alc.",
        "category":  "cerveja",
        "categoryName":  "Cervejas",
        "description":  "Cerveja Aldeana.Encorpada e de tons âmbar, com notas de caramelo e tostado, surpreende os paladares mais exigentes.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1203/conversions/Design-sem-nome-%2819%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  103,
        "name":  "Cerveja Artesanal IPA Garrafa 33cl. 6,5% Alc.",
        "category":  "cerveja",
        "categoryName":  "Cervejas",
        "description":  "Cerveja Aldeana.Amarga por tradição, mas equilibrada com nota cítricas, apresenta-se de cor laranja e com nuances de toranja e pinho.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1202/conversions/Design-sem-nome-%2818%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  102,
        "name":  "Cerveja Artesanal TRIGO Garrafa 33cl. 5,0% Alc.",
        "category":  "cerveja",
        "categoryName":  "Cervejas",
        "description":  "Cerveja Aldeana.Cerveja de trigo, leve e fresca, de aroma tropical e tons pálidos. Para se beber em qualquer ocasião.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1201/conversions/Design-sem-nome-%2817%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  101,
        "name":  "MENU DUO",
        "category":  "promocoes",
        "categoryName":  "PROMOÇÕES",
        "description":  "",
        "price":  21,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  100,
        "name":  "Oltre Egg",
        "category":  "escolha-o-hamburguer",
        "categoryName":  "Escolha o Hamburguer",
        "description":  "Pão artesanal, blend 100% vaca, queijo cheddar, bacon defumado, cebola caramelizada, ovo frito, molho Oltre e batata rústica.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1237/conversions/Design-sem-nome---2023-06-01T144737.897-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  99,
        "name":  "Oltre Special",
        "category":  "escolha-o-hamburguer",
        "categoryName":  "Escolha o Hamburguer",
        "description":  "Pão artesanal, blend 100% vaca, queijo cheddar, molho Oltre, bacon defumado, cebola caramelizada, alface, tomate, picles de pepino e batata rústica.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1236/conversions/Design-sem-nome-%2898%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  98,
        "name":  "Batata",
        "category":  "entradas",
        "categoryName":  "Entradas",
        "description":  "",
        "price":  10,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  97,
        "name":  "Oltre Vegetarian",
        "category":  "hot-sandwiches",
        "categoryName":  "Hot Sandwiches",
        "description":  "Pão artesanal, cogumelo portobello, courgette, beringela, tomate, onion rings, rúcula e molho oltre.Pão artesanal, cogumelo portobello, courgette, beringela, tomate, onion rings, rúcula e molho oltre..",
        "price":  12,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1214/conversions/Design-sem-nome-%2885%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  96,
        "name":  "Oltre Pulled Pork",
        "category":  "hot-sandwiches",
        "categoryName":  "Hot Sandwiches",
        "description":  "Pão artesanal, carne de porco fumada e desfiada, salada coleslaw e molho barbecue artesanal.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1217/conversions/Design-sem-nome-%2887%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  95,
        "name":  "Oltre Pulled Beef",
        "category":  "hot-sandwiches",
        "categoryName":  "Hot Sandwiches",
        "description":  "Pão artesanal, carne de vaca fumada e desfiada, salada coleslaw e molho barbecue artesanal.",
        "price":  11,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1216/conversions/Design-sem-nome-%2886%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  94,
        "name":  "Oltre triple smash",
        "category":  "smash-burgers",
        "categoryName":  "Smash Burgers",
        "description":  "Pão artesanal, 3 x 90gr do nosso blend 100% vaca prensado, queijo cheddar e molho oltre.",
        "price":  12,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1218/conversions/Design-sem-nome-%2890%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  93,
        "name":  "Oltre Smash (Opção Kids)",
        "category":  "smash-burgers",
        "categoryName":  "Smash Burgers",
        "description":  "Pão artesanal, 90gr do nosso blend 100% vaca prensado, queijo cheddar e molho oltre.",
        "price":  8,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1219/conversions/Design-sem-nome-%2888%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  92,
        "name":  "Oltre Double Smash",
        "category":  "smash-burgers",
        "categoryName":  "Smash Burgers",
        "description":  "Pão artesanal, 2 x 90gr do nosso blend 100% vaca prensado, queijo cheddar e molho oltre.",
        "price":  10,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1220/conversions/Design-sem-nome-%2889%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  91,
        "name":  "Oltre chimichurri",
        "category":  "burgers",
        "categoryName":  "Burgers",
        "description":  "Pão artesanal, 180gr do nosso blend 100% vaca, queijo provolone, cebola grelhada e molho chimichurri artesanal.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0121/1185/conversions/media-libraryT1bpes-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  90,
        "name":  "Oltre Chicken Special",
        "category":  "chicken-burgers",
        "categoryName":  "Chicken Burgers",
        "description":  "Pão artesanal, hambúrguer de peito de frango, queijo cheddar, bacon fumado, cebola caramelizada, alface, tomate e pickles artesanal de pepino e molho oltre.",
        "price":  11,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1221/conversions/Design-sem-nome-%2895%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  89,
        "name":  "Oltre Chicken Egg",
        "category":  "chicken-burgers",
        "categoryName":  "Chicken Burgers",
        "description":  "Pão artesanal, hambúrguer de peito de frango, queijo cheddar, ovo estrelado, bacon fumado, cebola caramelizada e molho oltre.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1222/conversions/Design-sem-nome-%2894%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  88,
        "name":  "Oltre Chicken Classic",
        "category":  "chicken-burgers",
        "categoryName":  "Chicken Burgers",
        "description":  "Pão artesanal, hambúrguer de peito de frango, queijo cheddar, alface, tomate, pickles artesanal de pepino e molho oltre.",
        "price":  10,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1223/conversions/Design-sem-nome-%2893%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  87,
        "name":  "Oltre Chicken Burger",
        "category":  "chicken-burgers",
        "categoryName":  "Chicken Burgers",
        "description":  "Pão artesanal, hambúrguer de peito de frango, queijo cheddar e molho oltre.",
        "price":  9,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1224/conversions/Design-sem-nome-%2891%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  86,
        "name":  "Oltre Chicken Bacon",
        "category":  "chicken-burgers",
        "categoryName":  "Chicken Burgers",
        "description":  "Pão artesanal, hambúrguer de peito de frango, queijo cheddar, bacon fumado, cebola caramelizada e molho oltre.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1225/conversions/Design-sem-nome-%2892%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  85,
        "name":  "Oltre Special",
        "category":  "burgers",
        "categoryName":  "Burgers",
        "description":  "Pão artesanal, blend 100% vaca, queijo cheddar, molho Oltre, bacon defumado, cebola caramelizada, alface, tomate, picles de pepino e batata rústica.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1228/conversions/Design-sem-nome-%2898%29-thumbnail.jpg",
        "badge":  "Mais Pedido"
    },
    {
        "id":  84,
        "name":  "Oltre Pepcream",
        "category":  "burgers",
        "categoryName":  "Burgers",
        "description":  "Pão artesanal, 180gr do nosso blend 100% vaca, molho de queijo e pepperoni.",
        "price":  13,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1229/conversions/Design-sem-nome-%2899%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  83,
        "name":  "Oltre Old School",
        "category":  "burgers",
        "categoryName":  "Burgers",
        "description":  "Pão artesanal, 180gr do nosso blend 100% vaca, queijo cheddar, pickles artesanal de pepino, cebola roxa, ketchup e mostarda.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1230/conversions/Design-sem-nome-%28100%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  82,
        "name":  "Oltre Egg",
        "category":  "burgers",
        "categoryName":  "Burgers",
        "description":  "Pão artesanal, 180gr do nosso blend 100% vaca, queijo cheddar, ovo estrelado, bacon fumado, cebola caramelizada e molho oltre.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1233/conversions/Design-sem-nome---2023-06-01T144737.897-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  81,
        "name":  "Oltre Classic",
        "category":  "burgers",
        "categoryName":  "Burgers",
        "description":  "Pão artesanal, 180gr do nosso blend 100% vaca, queijo cheddar, alface, tomate, pickles artesanal de pepino e molho oltre.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1231/conversions/Design-sem-nome---2023-06-01T144529.507-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  80,
        "name":  "Oltre Burger",
        "category":  "burgers",
        "categoryName":  "Burgers",
        "description":  "Pão artesanal, 180gr do nosso blend 100% vaca, queijo cheddar e molho oltre.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1226/conversions/Design-sem-nome-%2896%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  79,
        "name":  "Oltre Barbecue",
        "category":  "burgers",
        "categoryName":  "Burgers",
        "description":  "Pão artesanal, 180gr do nosso blend 100% vaca, queijo cheddar, bacon fumado, onion rings, pickles artesanal de pepino e molho barbecue artesanal.",
        "price":  13,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1232/conversions/Design-sem-nome---2023-06-01T144616.217-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  78,
        "name":  "Oltre Bacon",
        "category":  "burgers",
        "categoryName":  "Burgers",
        "description":  "Pão artesanal, 180gr do nosso blend 100% vaca, queijo cheddar, bacon fumado, cebola caramelizada e molho oltre.",
        "price":  11,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1227/conversions/Design-sem-nome-%2897%29-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  77,
        "name":  "Água Tônica",
        "category":  "escolha-a-bebida",
        "categoryName":  "ESCOLHA A BEBIDA",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  76,
        "name":  "Água com Gás",
        "category":  "escolha-a-bebida",
        "categoryName":  "ESCOLHA A BEBIDA",
        "description":  "",
        "price":  2,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  75,
        "name":  "Água Sem Gás",
        "category":  "escolha-a-bebida",
        "categoryName":  "ESCOLHA A BEBIDA",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  74,
        "name":  "Ice Tea Pêssego",
        "category":  "escolha-a-bebida",
        "categoryName":  "ESCOLHA A BEBIDA",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  73,
        "name":  "Ice Tea Manga",
        "category":  "escolha-a-bebida",
        "categoryName":  "ESCOLHA A BEBIDA",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  72,
        "name":  "Ice Tea Limão",
        "category":  "escolha-a-bebida",
        "categoryName":  "ESCOLHA A BEBIDA",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  71,
        "name":  "Fanta",
        "category":  "escolha-a-bebida",
        "categoryName":  "ESCOLHA A BEBIDA",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  70,
        "name":  "Seven Up",
        "category":  "escolha-a-bebida",
        "categoryName":  "ESCOLHA A BEBIDA",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  69,
        "name":  "Guaraná",
        "category":  "escolha-a-bebida",
        "categoryName":  "ESCOLHA A BEBIDA",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  68,
        "name":  "Cola Zero",
        "category":  "escolha-a-bebida",
        "categoryName":  "ESCOLHA A BEBIDA",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  67,
        "name":  "Pimenta Malagueta",
        "category":  "adicionar-extras",
        "categoryName":  "ADICIONAR EXTRAS",
        "description":  "",
        "price":  1,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  66,
        "name":  "Jalapenõ",
        "category":  "adicionar-extras",
        "categoryName":  "ADICIONAR EXTRAS",
        "description":  "",
        "price":  1,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  65,
        "name":  "Onion Rings",
        "category":  "adicionar-extras",
        "categoryName":  "ADICIONAR EXTRAS",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  64,
        "name":  "Pepperoni",
        "category":  "adicionar-extras",
        "categoryName":  "ADICIONAR EXTRAS",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  63,
        "name":  "Rúcula",
        "category":  "adicionar-extras",
        "categoryName":  "ADICIONAR EXTRAS",
        "description":  "",
        "price":  1,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  62,
        "name":  "Courgete",
        "category":  "adicionar-extras",
        "categoryName":  "ADICIONAR EXTRAS",
        "description":  "",
        "price":  1,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  61,
        "name":  "Berinjela",
        "category":  "adicionar-extras",
        "categoryName":  "ADICIONAR EXTRAS",
        "description":  "",
        "price":  1,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  60,
        "name":  "Cogumelo Portobello",
        "category":  "adicionar-extras",
        "categoryName":  "ADICIONAR EXTRAS",
        "description":  "",
        "price":  1,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  59,
        "name":  "Cebola roxa",
        "category":  "adicionar-extras",
        "categoryName":  "ADICIONAR EXTRAS",
        "description":  "",
        "price":  1,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  58,
        "name":  "Cebola caramelizada",
        "category":  "adicionar-extras",
        "categoryName":  "ADICIONAR EXTRAS",
        "description":  "",
        "price":  1,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  57,
        "name":  "Pickles de pepino artesanal",
        "category":  "adicionar-extras",
        "categoryName":  "ADICIONAR EXTRAS",
        "description":  "",
        "price":  1,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  56,
        "name":  "Alface",
        "category":  "adicionar-extras",
        "categoryName":  "ADICIONAR EXTRAS",
        "description":  "",
        "price":  1,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  55,
        "name":  "Tomate",
        "category":  "adicionar-extras",
        "categoryName":  "ADICIONAR EXTRAS",
        "description":  "",
        "price":  1,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  53,
        "name":  "Queijo Cheddar",
        "category":  "adicionar-extras",
        "categoryName":  "ADICIONAR EXTRAS",
        "description":  "",
        "price":  1,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  52,
        "name":  "Ovo Frito",
        "category":  "adicionar-extras",
        "categoryName":  "ADICIONAR EXTRAS",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  50,
        "name":  "Bacon",
        "category":  "adicionar-extras",
        "categoryName":  "ADICIONAR EXTRAS",
        "description":  "",
        "price":  2,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  49,
        "name":  "Molho",
        "category":  "adicionar-extras",
        "categoryName":  "ADICIONAR EXTRAS",
        "description":  "",
        "price":  1,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  48,
        "name":  "Troca por batata doce",
        "category":  "adicionar-extras",
        "categoryName":  "ADICIONAR EXTRAS",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  47,
        "name":  "Coca cola",
        "category":  "escolha-a-bebida",
        "categoryName":  "ESCOLHA A BEBIDA",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  46,
        "name":  "Não, obrigado",
        "category":  "escolha-a-bebida",
        "categoryName":  "ESCOLHA A BEBIDA",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "",
        "badge":  ""
    },
    {
        "id":  44,
        "name":  "Sumol de Ananás",
        "category":  "bebidas",
        "categoryName":  "Bebidas",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1138/media-library1bJ4JA",
        "badge":  ""
    },
    {
        "id":  43,
        "name":  "7-Up",
        "category":  "bebidas",
        "categoryName":  "Bebidas",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1095/media-library5kUjH8",
        "badge":  ""
    },
    {
        "id":  42,
        "name":  "Sidra de Maçã",
        "category":  "bebidas",
        "categoryName":  "Bebidas",
        "description":  "",
        "price":  5,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1137/media-libraryJOLiEx",
        "badge":  ""
    },
    {
        "id":  41,
        "name":  "Cerveja sem Alcool",
        "category":  "bebidas",
        "categoryName":  "Bebidas",
        "description":  "",
        "price":  4,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1103/media-libraryP4Nzyp",
        "badge":  ""
    },
    {
        "id":  40,
        "name":  "Ice Tea Pessego",
        "category":  "bebidas",
        "categoryName":  "Bebidas",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1111/media-libraryNGquV1",
        "badge":  ""
    },
    {
        "id":  39,
        "name":  "Ice Tea Manga",
        "category":  "bebidas",
        "categoryName":  "Bebidas",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1110/media-libraryBRHzek",
        "badge":  ""
    },
    {
        "id":  38,
        "name":  "Ice Tea Limão",
        "category":  "bebidas",
        "categoryName":  "Bebidas",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1109/media-library7jnjfL",
        "badge":  ""
    },
    {
        "id":  37,
        "name":  "Guaraná",
        "category":  "bebidas",
        "categoryName":  "Bebidas",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1108/media-libraryp3hlVq",
        "badge":  ""
    },
    {
        "id":  36,
        "name":  "Fanta",
        "category":  "bebidas",
        "categoryName":  "Bebidas",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1106/media-libraryZoQTmr",
        "badge":  ""
    },
    {
        "id":  35,
        "name":  "Coca Cola Zero",
        "category":  "bebidas",
        "categoryName":  "Bebidas",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1105/media-libraryZoq7FS",
        "badge":  ""
    },
    {
        "id":  34,
        "name":  "Coca Cola",
        "category":  "bebidas",
        "categoryName":  "Bebidas",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1104/media-libraryx6bvjz",
        "badge":  ""
    },
    {
        "id":  33,
        "name":  "Água tônica",
        "category":  "bebidas",
        "categoryName":  "Bebidas",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1098/media-libraryL2ENJe",
        "badge":  ""
    },
    {
        "id":  32,
        "name":  "Água com gás",
        "category":  "bebidas",
        "categoryName":  "Bebidas",
        "description":  "",
        "price":  2,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1096/media-libraryFaFQCi",
        "badge":  ""
    },
    {
        "id":  31,
        "name":  "Água sem gás",
        "category":  "bebidas",
        "categoryName":  "Bebidas",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1097/media-libraryzZZhvC",
        "badge":  ""
    },
    {
        "id":  30,
        "name":  "Saco",
        "category":  "sacos",
        "categoryName":  "Sacos",
        "description":  "Proibição de disponibilização gratuita de sacos de caixa, com ou sem pega, feitos de qualquer material estabelecida no n.º 4 do artigo 25.º do Decreto-Lei 152-D/2017, de 11 de Dezembro, aditado pelo Decreto-Lei 102-D/2020, de 10 de dezembro.",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1136/media-libraryzYloEB",
        "badge":  ""
    },
    {
        "id":  26,
        "name":  "Fraldinha com batatas",
        "category":  "entradas",
        "categoryName":  "Entradas",
        "description":  "",
        "price":  14,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1107/media-librarydADD6j",
        "badge":  ""
    },
    {
        "id":  25,
        "name":  "Picanha com batatas",
        "category":  "entradas",
        "categoryName":  "Entradas",
        "description":  "",
        "price":  14,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1135/media-libraryTRipmR",
        "badge":  ""
    },
    {
        "id":  24,
        "name":  "Oltre Chicken Wings",
        "category":  "entradas",
        "categoryName":  "Entradas",
        "description":  "",
        "price":  8,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1292/conversions/wings-sem-batata-thumbnail.jpg",
        "badge":  ""
    },
    {
        "id":  23,
        "name":  "Oltre Cheese Balls",
        "category":  "entradas",
        "categoryName":  "Entradas",
        "description":  "",
        "price":  8,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1115/media-libraryJC9Zk1",
        "badge":  ""
    },
    {
        "id":  22,
        "name":  "Batata Com Queijo e Pepperoni",
        "category":  "entradas",
        "categoryName":  "Entradas",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1100/media-libraryRAf42q",
        "badge":  ""
    },
    {
        "id":  21,
        "name":  "Batata Com Queijo e Bacon",
        "category":  "entradas",
        "categoryName":  "Entradas",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1099/media-libraryPSimjd",
        "badge":  ""
    },
    {
        "id":  20,
        "name":  "Oltre Onion Rings",
        "category":  "entradas",
        "categoryName":  "Entradas",
        "description":  "",
        "price":  7,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1127/media-librarypOK3UH",
        "badge":  ""
    },
    {
        "id":  19,
        "name":  "Batata Doce",
        "category":  "entradas",
        "categoryName":  "Entradas",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1101/media-libraryZeseLP",
        "badge":  ""
    },
    {
        "id":  18,
        "name":  "Batata Rústica",
        "category":  "entradas",
        "categoryName":  "Entradas",
        "description":  "",
        "price":  0,
        "salePrice":  null,
        "inStock":  true,
        "image":  "https://lojadodia.s3.eu-central-1.amazonaws.com/lojadodia/0147/1102/media-librarypIzM0t",
        "badge":  ""
    }
];

window.OLTRE_CATEGORIES = [
    {
        "icon":  "🔥",
        "name":  "Promoções",
        "id":  "promocoes"
    },
    {
        "icon":  "🍟",
        "name":  "Entradas",
        "id":  "entradas"
    },
    {
        "icon":  "🍔",
        "name":  "Burgers Clássicos",
        "id":  "burgers"
    },
    {
        "icon":  "💥",
        "name":  "Smash Burgers",
        "id":  "smash-burgers"
    },
    {
        "icon":  "🍗",
        "name":  "Chicken Burgers",
        "id":  "chicken-burgers"
    },
    {
        "icon":  "🥪",
        "name":  "Hot Sandwiches",
        "id":  "hot-sandwiches"
    },
    {
        "icon":  "🥤",
        "name":  "Bebidas",
        "id":  "bebidas"
    },
    {
        "icon":  "🍺",
        "name":  "Cervejas",
        "id":  "cerveja"
    },
    {
        "icon":  "🍰",
        "name":  "Sobremesas",
        "id":  "sobremesas"
    }
];
window.OLTRE_DEFAULT_CONFIG = {
    "topNotice":  "🍔 Entregas e Takeaway em Sesimbra | Pagamento seguro por MB WAY e Multibanco",
    "deliveryFee":  2.5,
    "heroSubtitle":  "Hambúrgueres artesanais de verdade em pão brioche, com carne 100% novilho e molhos secretos.",
    "heroTitle":  "Io preferisco andare Oltre",
    "statusText":  "Aberto hoje das 12:00 às 15:00 e das 19:00 às 23:00",
    "location":  "Sesimbra",
    "storeName":  "Oltre Hamburgueria",
    "status":  "open",
    "minOrder":  15,
    "whatsapp":  "351216028131",
    "phone":  "216 028 131",
    "primaryColor":  "#DCAC58",
    "bannerUrl":  "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format\u0026fit=crop\u0026w=1600\u0026q=80",
    "currency":  "€",
    "address":  "Rua Doutor Peixoto Correia, 67, 2970-752 Sesimbra"
};
